[package]
name = "csvtutor"
version = "0.1.0"
authors = ["root"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

csv = "1"
unidecode = "0.3.0"
chrono = "0.4"
postgres = "0.17.5"
rocket = "0.4.6"
